name: TeaSpoon
main: CortexPE\Main
version: 1.1.3
api: [2.0.0, 3.0.0, 4.0.0, 3.8.3]
load: STARTUP
author: CortexPE
description: A PLUGIN to Extend PMMP's Functionality without completely changing it.
website: https://CortexPE.xyz
